In [1]:
import numpy as np
import pandas as pd

In [8]:
# Create a DataFrame of 5 students with columns: Name, Age, Marks.
df = pd.DataFrame({
    'Name': ['Shristi', 'Anjali', 'Rishabh', 'Rudra', 'Fatima'],
    'Age': [19, 20, 20, 19, 18],
    'Marks': [49, 91, 47, 84, 94]
})

In [9]:
# Display the first 3 rows and last 2 rows of the DataFrame.
pd.concat([df.head(3), df.tail(2)])

Name  Age  Marks
0  Shristi   19     49
1   Anjali   20     91
2  Rishabh   20     47
3    Rudra   19     84
4   Fatima   18     94

In [10]:
# Show the shape of the DataFrame (rows × columns).
df.shape

(5, 3)

In [11]:
# Access only the Name column from the DataFrame.
df['Name']

0    Shristi
1     Anjali
2    Rishabh
3      Rudra
4     Fatima
Name: Name, dtype: object

In [12]:
# Filter all rows where Marks are greater than 50.
df[df['Marks'] > 50]

Name  Age  Marks
1  Anjali   20     91
3   Rudra   19     84
4  Fatima   18     94

In [14]:
# Add a new column Result with values: "Pass" or "Fail".
df['Result'] = np.where(df['Marks'] > 50, 'Pass', 'Fail')
df

Name  Age  Marks Result
0  Shristi   19     49   Fail
1   Anjali   20     91   Pass
2  Rishabh   20     47   Fail
3    Rudra   19     84   Pass
4   Fatima   18     94   Pass

In [15]:
# Update the Marks of the first student to 95.
df.loc[0, 'Marks'] = 95

In [16]:
df

Name  Age  Marks Result
0  Shristi   19     95   Fail
1   Anjali   20     91   Pass
2  Rishabh   20     47   Fail
3    Rudra   19     84   Pass
4   Fatima   18     94   Pass

In [19]:
# Delete the Result column from the DataFrame.
df.drop('Result', axis=1, inplace=True)

In [20]:
df

Name  Age  Marks
0  Shristi   19     95
1   Anjali   20     91
2  Rishabh   20     47
3    Rudra   19     84
4   Fatima   18     94

In [21]:
# Sort the DataFrame by Marks in descending order.
df.sort_values('Marks', ascending=False)

Name  Age  Marks
0  Shristi   19     95
4   Fatima   18     94
1   Anjali   20     91
3    Rudra   19     84
2  Rishabh   20     47

In [23]:
# Count the number of unique names in the Name column.
df['Name'].nunique()

5

In [24]:
# Create a DataFrame of Sales with columns: Region, Product, Sales.
df2 = pd.DataFrame({
    'Region': ['Kutchery', 'Civil Lines', 'Rani Chauk', 'Gandhi Nagar', 'Lakshmi Complex'],
    'Product': ['Cosmetics', 'Cosmetics', 'Medics', 'Clothing', 'Footwears'],
    'Sales': [124, 57, 48, 91, 110]
})
df2

Region    Product  Sales
0         Kutchery  Cosmetics    124
1      Civil Lines  Cosmetics     57
2       Rani Chauk     Medics     48
3     Gandhi Nagar   Clothing     91
4  Lakshmi Complex  Footwears    110

In [25]:
# Calculate the total sales.
df2['Sales'].sum()

430

In [31]:
# Calculate the average sales per product.
df2.groupby('Product')['Sales'].mean()

Product
Clothing      91.0
Cosmetics     90.5
Footwears    110.0
Medics        48.0
Name: Sales, dtype: float64

In [32]:
# Count how many times each product appears in the dataset.
df2['Product'].value_counts()

Product
Cosmetics    2
Medics       1
Clothing     1
Footwears    1
Name: count, dtype: int64

In [34]:
# Find maximum and minimum sales per region using groupby and agg.
df2.groupby('Region')['Sales'].agg(['min', 'max'])

min  max
Region                   
Civil Lines       57   57
Gandhi Nagar      91   91
Kutchery         124  124
Lakshmi Complex  110  110
Rani Chauk        48   48

In [37]:
# Create a pivot table showing total sales per Region vs Product.
pivot = pd.pivot_table(df2, values='Sales', index='Region', columns='Product', aggfunc='sum')
print(pivot)

Product          Clothing  Cosmetics  Footwears  Medics
Region                                                 
Civil Lines           NaN       57.0        NaN     NaN
Gandhi Nagar         91.0        NaN        NaN     NaN
Kutchery              NaN      124.0        NaN     NaN
Lakshmi Complex       NaN        NaN      110.0     NaN
Rani Chauk            NaN        NaN        NaN    48.0


In [39]:
# Create a pivot table showing average sales per Region.
pivot = pd.pivot_table(df2, values='Sales', index='Region', aggfunc='mean')
print(pivot)

                 Sales
Region                
Civil Lines       57.0
Gandhi Nagar      91.0
Kutchery         124.0
Lakshmi Complex  110.0
Rani Chauk        48.0


In [41]:
# Create a NumPy array of numbers from 1 to 10.
num_arr = np.arange(1, 11)
num_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Find the sum, mean, and standard deviation of the array.
sum = num_arr.sum()
mean = num_arr.mean()
std_dev = num_arr.std()
print(f"Sum: {sum}, Mean: {mean}, Standard Deviation: {std_dev}")

Sum: 55, Mean: 5.5, Standard Deviation: 2.8722813232690143


In [43]:
# Reshape an array of numbers from 1 to 12 into a 3×4 matrix.
num_arr2 = np.arange(1, 13).reshape(3, 4)
num_arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# Create a 2D NumPy array of random integers (3×3).
random_2d = np.random.randint(low=0, high=100, size=(3, 3))
random_2d

array([[52, 17, 91],
       [95, 14, 53],
       [39, 96, 50]])

In [46]:
# Find the sum of each row and sum of each column.
row_sums = np.sum(random_2d, axis=1)
col_sums = np.sum(random_2d, axis=0)
print(f"Rows Sum: {row_sums}, Cols Sum: {col_sums}")

Rows Sum: [160 162 185], Cols Sum: [186 127 194]


In [47]:
# Multiply two 3×3 matrices using NumPy.
A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randint(0, 10, size=(3, 3))

result = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A × B:\n", result)

Matrix A:
 [[2 4 8]
 [7 3 6]
 [9 5 0]]
Matrix B:
 [[8 8 2]
 [3 5 8]
 [3 0 9]]
A × B:
 [[ 52  36 108]
 [ 83  71  92]
 [ 87  97  58]]


In [48]:
# Find the maximum and minimum value in the array and their indices.
array = np.random.randint(0, 100, size=(3, 3))
print("Array:\n", array)

max_val = np.max(array)
min_val = np.min(array)

max_index = np.unravel_index(np.argmax(array), array.shape)
min_index = np.unravel_index(np.argmin(array), array.shape)

print("Max value:", max_val, "at index", max_index)
print("Min value:", min_val, "at index", min_index)

Array:
 [[71  0 69]
 [93 42 88]
 [47 77 33]]
Max value: 93 at index (1, 0)
Min value: 0 at index (0, 1)


In [50]:
# Slice a NumPy array to get only even numbers.
array = np.random.randint(0, 20, size=(3, 4))
print("Original array:\n", array)

even_numbers = array[array % 2 == 0]
print("Even numbers:\n", even_numbers)

Original array:
 [[ 1  9  2  3]
 [19 17 10 11]
 [ 2 14 16  3]]
Even numbers:
 [ 2 10  2 14 16]
