In [1]:
import numpy as np

**ARRAY OPERATIONS**

***Arithmetic operations***

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

***Broadcasting***

In [9]:
l = [10, 20, 30 , 40]
arr = np.array(l)

In [10]:
arr + 10

array([20, 30, 40, 50])

In [12]:
arr2 = np.arange(1, 26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

***Deep and Shallow copy***

In [32]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
slice_a = a[:5]
slice_a = slice_a * 10
slice_a

array([10, 20, 30, 40, 50])

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a[4:6] * 10

array([50, 60])

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a
b = a.copy()

In [38]:
b[0] = 99

In [39]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
b = a
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

***Matrix operations***

In [43]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [44]:
A

array([[1, 2],
       [3, 4]])

In [45]:
B

array([[5, 6],
       [7, 8]])

In [51]:
# Matrix Multiplication

A @ B

array([[19, 22],
       [43, 50]])

In [52]:
# Other way

np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
# Transpose

A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

***Stacking Array***

In [58]:
# Note -> We can't stack matrix but we can stack vectors

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [59]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

***Splitting Array***

In [63]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
a = np.vsplit(c, 2)

In [69]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
