In [2]:
import numpy as np

### Basic Array Creation

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1, 2, 3.5]
a

[1, 2, 3.5]

In [5]:
np.array(a)

array([1. , 2. , 3.5])

In [6]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array generation function

In [10]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.zeros((4, 8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.ones((6, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### Random generation function

In [27]:
# rand -> useful for normalization (0 to 1)
np.random.rand(10)

array([0.56007904, 0.21487795, 0.59324318, 0.12477311, 0.94355931,
       0.12903183, 0.11040298, 0.60910013, 0.48803631, 0.54551392])

In [28]:
# randn -> useful for standardisation (-3 to 3)
np.random.randn(10)

array([ 0.58410329, -0.71018386,  0.14299438,  0.40503948, -1.03069744,
        0.31654   ,  1.88220458, -0.27285503, -0.20926625,  0.2357503 ])

In [29]:
np.random.randint(6)

1

In [30]:
np.random.randint(10, 20, 10)

array([18, 13, 10, 19, 17, 13, 19, 17, 11, 13])

### Array attributes

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr.shape

(3, 3)

In [33]:
arr.size

9

In [34]:
arr.dtype

dtype('int32')

### Array methods

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.min()

1

In [37]:
arr.max()

9

In [38]:
arr.sum()

45

In [41]:
# axis = 0 means we are going for the columns

np.sum(arr, axis=0)

array([12, 15, 18])

In [42]:
# axis = 1 means we are going for the rows

np.sum(arr, axis=1)

array([ 6, 15, 24])

In [43]:
arr.mean()

5.0

In [44]:
arr.std()

2.581988897471611

In [46]:
# argmax means max element index

arr.argmax()

8

In [47]:
# argmin means min element index

arr.argmin()

0

### Reshaping and resizing

In [49]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
# in reshape we will have to give the shape which basically means how we want to change the shape of the array, if there are 25 elements then we can go for 5 rows and 5 columns.
# in our case we had 30 elements in our array so we went for 6 rows and 5 columns we can also go for 5 rows and 6 columns though.

arr = arr.reshape(6, 5)

In [58]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])