In [1]:
import numpy as np

**NUMPY INDEXING AND SLICING OF VECTORS**

In [3]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

17

In [5]:
arr[1:5]

array([12, 13, 14, 15])

In [6]:
arr_slice = arr[3::2]

In [7]:
arr_slice

array([14, 16, 18, 20])

**NUMPY INDEXING AND SLICING OF MATRIX**

In [9]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[4]

array([21, 22, 23, 24, 25])

In [12]:
arr[5, 4]

30

In [13]:
slice_arr = arr[0:2, 1:3]
slice_arr

array([[2, 3],
       [7, 8]])

In [15]:
slice_arr = arr[3:, 3:]
slice_arr

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
slice_arr = arr[:, 2]
slice_arr

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [18]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [21]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])