In [1]:
import numpy as np

In [2]:
# Create a NumPy array of 10 random integers between 1 and 100. Find its mean.
array = np.random.randint(1, 101, size=10)
mean = np.mean(array)
mean

68.3

In [3]:
# Calculate the median of the array: [10, 5, 8, 12, 3, 7].
array = [10, 5, 8, 12, 3, 7]
median = np.median(array)
median

7.5

In [4]:
# Generate an array of 15 random numbers between 1 and 50. Find its standard deviation.
array = np.random.randint(1, 51, size=15)
std_dev = np.std(array)
std_dev

12.336756281760435

In [5]:
# Create a 3x3 array with values from 1 to 9. Find the row-wise mean.
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
row_mean = np.mean(array, axis=1)
row_mean

array([2., 5., 8.])

In [6]:
# For the array [4, 6, 8, 10, 12], calculate mean, median, std.
array = [4, 6, 8, 10, 12]
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)

print("Mean: ", mean)
print("Median: ", median)
print("Standard Deviation: ", std_dev)

Mean:  8.0
Median:  8.0
Standard Deviation:  2.8284271247461903


In [7]:
# Generate a 5x5 NumPy array of random integers (0 to 100). Find the overall mean.
array = np.random.randint(0, 101, size=(5, 5))
mean = np.mean(array)
mean

43.96

In [8]:
# Create an array of 50 random integers and calculate the standard deviation.
array = np.random.randint(1, 51, size=50)
std_dev = np.std(array)
std_dev

12.989611233597408

In [9]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
non_zero_indices

(array([0, 1, 4], dtype=int64),)

In [10]:
# You have an 2D array, print array element [[7,4]]:
# [[2,3,4
# 5,7,4
# 8,9,0]]

array = np.array([[2, 3, 4], [5, 7, 4], [8, 9, 0]])
sub_array = array[1:2, 1:]
sub_array

array([[7, 4]])

In [12]:
# Create 2 array of 2-Dimension and then perform matrix multiplication on them.
arr1 = np.array([[1, 2, 3], [4, 5, 6]]).reshape(2, 3)
arr2 = np.array([[7, 8, 9], [10, 11, 12]]).reshape(2, 3)
arr2_T = arr2.T
matrix_mul = np.dot(arr1, arr2_T)
matrix_mul

array([[ 50,  68],
       [122, 167]])