In [1]:
import numpy as np

**Level 1: Basics**

In [2]:
# Create a NumPy array of numbers from 1 to 20.
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
# Create a 3×3 matrix with values ranging from 0 to 8.
arr2 = np.arange(0, 9).reshape(3, 3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# Generate an array of 10 zeros and another of 10 ones.
arr3 = np.zeros(10)
arr4 = np.ones(10)
print(arr3, arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# Create a random float array of size 5 between 0 and 1.
arr5 = np.random.ranf(5)
arr5

array([0.93640977, 0.05772917, 0.92073008, 0.9514153 , 0.90636858])

**Level 2: Array Operations**

In [6]:
# Given an array [1,2,3,4,5], square every element.
arr6 = [1,2,3,4,5]
arr7 = [i ** 2 for i in arr6]
arr7

[1, 4, 9, 16, 25]

In [7]:
# Create a 5×5 identity matrix.
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Extract all even numbers from an array of 1–30.
arr8 = np.arange(1, 31)
even_numbers = arr8[arr8 % 2 == 0]
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [17]:
# Replace all odd numbers in an array of 1–20 with -1.
arr9 = np.arange(1, 21)
arr9[arr9 % 2 != 0] = -1
arr9

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1,
       18, -1, 20])

**Level 3: Statistics & Math**

In [27]:
# Generate an array of 100 random numbers and find its mean, median, and standard deviation.
arr10 = np.random.rand(100)
mean = np.mean(arr10)
median = np.median(arr10)
std_dev = np.std(arr10)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")

Mean: 0.5209890959867436
Median: 0.5251890432567905
Standard Deviation: 0.2823496603474825


In [39]:
# Create a 4×4 matrix of random integers (1–100). Find the maximum value in each row.
matrix = np.random.randint(1, 101, size=(4, 4))
row_max = np.max(matrix, axis=1)

print("Matrix:")
print(matrix)
print("\nMaximum value in each row:")
print(row_max)

Matrix:
[[73 92 26 84]
 [56 73  2 43]
 [52  4 60 97]
 [47 77  6 51]]

Maximum value in each row:
[92 73 97 77]


**Level 4: Data Science-Oriented**

In [41]:
# Create a 2D NumPy array representing exam scores of 5 students in 3 subjects. Find the average score of each student.
scores = np.random.randint(0, 101, size=(5, 3))
student_averages = np.mean(scores, axis=1)
print("Exam Scores (Students × Subjects):")
print(scores)
print("\nAverage Score of Each Student:")
print(student_averages)

Exam Scores (Students × Subjects):
[[63  7 87]
 [75 54 36]
 [60 53 81]
 [88  9 49]
 [87 10  0]]

Average Score of Each Student:
[52.33333333 55.         64.66666667 48.66666667 32.33333333]


In [43]:
# Standardize (z-score normalize) a NumPy array of 1D data.
data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
std = np.std(data)
z_scores = (data - mean) / std
print("Original data: ", data)
print("Standardized (z-scores): ", z_scores)

Original data:  [10 20 30 40 50]
Standardized (z-scores):  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
# Flatten a 3D array into 1D.
arr12 = np.array([[[12, 23], [34, 45], [64, 77]]])
arr12.flatten()

array([12, 23, 34, 45, 64, 77])

In [48]:
# Reshape a 1D array of 12 numbers into a 3×4 matrix and then transpose it.
arr13 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(3, 4).T
arr13

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

**Level 5: Challenge**

In [49]:
# Create a 10×10 matrix where the border elements are 1 and the inside is 0.
matrix = np.ones((10, 10), dtype=int)
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [51]:
# Given two arrays a and b, find all elements that are common.
a = [1, 2, 3, 4]
b = [4, 5, 6, 7]
c = np.intersect1d(a, b)
c

array([4])

In [55]:
# Simulate 1000 coin flips using np.random.choice and count how many times you got heads.
coin_flips = np.random.choice(['Heads', 'Tails'], size=1000)
heads_count = np.sum(coin_flips == 'Heads')
print(f"Number of Heads: {heads_count}")

Number of Heads: 494


In [58]:
# Create a matrix of shape (6,6) with values 1–36 and extract the submatrix in the center (4×4 block).
matrix = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]).reshape(6, 6)
submatrix = matrix[1:5, 1:5]
submatrix

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])