In [1]:
import numpy as np

In [2]:
# Create a 1D array of numbers from 1 to 10.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Reshape your array into a 2D 2×5 matrix.
reshape = arr.reshape(2, 5)
reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
# Reshape it again into a 5×2 matrix.
reshape_again = reshape.reshape(5, 2)
reshape_again

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
# From the 2×5 matrix, extract the first row.
reshape_first_row = reshape[:1]
reshape_first_row

array([[1, 2, 3, 4, 5]])

In [10]:
# From the same matrix, extract the last column.
reshape_last_row = reshape[-1]
reshape_last_row

array([ 6,  7,  8,  9, 10])

In [11]:
# Get the middle 3 numbers from your original 1D array (numbers 4, 5, 6).
middle_numbers = arr[3:6]
middle_numbers

array([4, 5, 6])

In [14]:
# Square every number in your 1D array.
square_numbers = arr**2
square_numbers

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [17]:
# Add 10 to every element in your 2×5 matrix.
added_reshape = reshape + 10
added_reshape

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
# Multiply your 5×2 matrix by 2 (elementwise).
multiplied_reshape_again = reshape_again * 2
multiplied_reshape_again

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [24]:
# From the original array of 1–10, extract all even numbers.
for i in arr % 2 == 0:
    print(i)

False
True
False
True
False
True
False
True
False
True


In [27]:
# Replace all odd numbers with -1.
arr[arr % 2 != 0] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [28]:
# Generate an array of 20 random integers between 1 and 100.
random_int = np.random.randint(1, 101, size=20)
random_int

array([56, 47, 12, 94, 94, 68, 97, 81,  2, 56,  9, 34, 73, 39, 78, 50, 61,
       82,  4, 94])

In [29]:
# Find the mean, median, and standard deviation of this array.
mean = np.mean(random_int)
median = np.median(random_int)
std_dev = np.std(random_int)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard deviation: {std_dev}")

Mean: 56.55
Median: 58.5
Standard deviation: 30.744877622134062


In [30]:
# Find the maximum value in this array and its index.
max_value = np.max(random_int)
max_value

97

In [31]:
# Imagine this array is exam scores of 20 students. Standardize it (z-score normalization).
z_scores = (random_int - mean) / std_dev
z_scores

array([-0.01788916, -0.31062085, -1.44902187,  1.21808909,  1.21808909,
        0.37241976,  1.31566632,  0.79525443, -1.7742793 , -0.01788916,
       -1.5465991 , -0.73345551,  0.53504848, -0.5708268 ,  0.6976772 ,
       -0.21304362,  0.14473956,  0.82778017, -1.70922781,  1.21808909])

In [33]:
# Reshape it into a 4×5 “classroom” matrix. Find the average score of each row (each row = one group of 5 students).
classroom = z_scores.reshape(4, 5)
avg_classroom = np.average(classroom, axis=1)
avg_classroom

array([ 0.13172926,  0.13823441, -0.32363115,  0.05366748])

In [34]:
# Create a 6×6 matrix with numbers 1 to 36.
matrix = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]).reshape(6, 6)
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [35]:
# Extract the 4×4 submatrix in the center.
submatrix = matrix[1:5, 1:5]
submatrix

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [36]:
# Transpose this submatrix.
submatrix.T

array([[ 8, 14, 20, 26],
       [ 9, 15, 21, 27],
       [10, 16, 22, 28],
       [11, 17, 23, 29]])

In [38]:
# Simulate 1000 coin flips (H or T) using NumPy. Count how many H you got.
flips = np.random.choice(['H', 'T'], size=1000)
num_heads = np.count_nonzero(flips == 'H')
print(f"Number of Heads: {num_heads}")

Number of Heads: 483
